name: E2E

on: [push, pull_request]

jobs:
  e2e:
    name: End to End Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Run checks
      run: yarn test
